CREATE TABLE CLIENTE(
    CODIGO INT NOT NULL PRIMARY KEY,
    NOME TEXT,
    ENDERECO TEXT,
    APOLICE_FK FOREIGN KEY REFERENCES APOLICE(CODIGO)
)

CREATE TABLE APOLICE(
    CODIGO INT NOT NULL PRIMARY KEY,
    VALOR FLOAT,
    CARRO_FK INT FOREIGN KEY REFERENCES CARRO(CODIGO)
)

CREATE TABLE CARRO(
    CODIGO INT NOT NULL PRIMARY KEY,
    MARCA TEXT,
    APOLICE_FK  FOREIGN KEY REFERENCES APOLICE(CODIGO),
    ACIDENTES_FK  FOREIGN KEY REFERENCES ACIDENTES(CODIGO)
)

CREATE TABLE ACIDENTE(
    CODIGO INT NOT NULL PRIMARY KEY,
    HORA TEXT,
    DIA TEXT,
    LOCALIDADE TEXT
)
